### PR TITLE
Added entity & event coreference options for ACE pre-processing.

### PR DESCRIPTION
**Pull request by khuangaf**

### CODE REVIEW

**Comment by dwadden** [comment]
This looks great, thanks for adding!

One issue: right now, I rely on the code here https://github.com/dwadden/dygiepp/blob/allennlp-v1/dygie/data/dataset_readers/document.py to load in and represent documents. It's useful for displaying the data in a more human-readable form, and also for span arithmetic.

Your entity clusters should work fine with this since we already have entity coreference for other datasets.

But, event coreference will break this code. Can you update this code so that it can handle event coreference as well? The code for creating clusters is here: https://github.com/dwadden/dygiepp/blob/allennlp-v1/dygie/data/dataset_readers/document.py#L652. You should be able to do a similar thing but for even clusters.

Let me know if this seems doable. If not, I can just accept the PR as is with a warning that event clusters will break the data loading code.

**Comment by khuangaf** [comment]
No problem! Can you provide a use case of this `document.py` so that I can call and test event coreference? Would be very interested in how you create the human-readable form:) Thanks!

**Comment by dwadden** [comment]
Example here: https://github.com/dwadden/dygiepp/blob/allennlp-v1/notebooks/document.ipynb. Let me know if you've got questions. It's not the most human-readable thing ever, but it's better than looking at raw json...

**Comment by khuangaf** [comment]
Thanks it looks awesome! I will try to handle event clusters on the `document.py` script and test it on this notebook.

**Comment by dwadden** [comment]
OK great, thanks!

If you have the bandwidth, it would be awesome if you could modify the [split method](https://github.com/dwadden/dygiepp/blob/allennlp-v1/dygie/data/dataset_readers/document.py#L184) so that it will correctly split coreference clusters. But no worries if you don't have time.

**Comment by khuangaf** [comment]
Sure no problem!

Im currently working on a paper submission. Will PR again after that :)

**Comment by dwadden** [comment]
Thanks, much appreciated! Good luck with the deadline.

**Comment by khuangaf** [comment]
Hi @dwadden! I just modified `document.py` to handle event clusters. The split method for coreference is still not solved, tho. The method is a bit tricky (e.g.  how to determine the cluster id for clusters in the split documents & do you want to merge it back after split), which may need further discussion. I think it would be practical to do a separate pull request for that part. Please let me know if there is any problem :) Thanks!

**Comment by dwadden** [comment]
Looks good, thanks! Agreed, cluster splitting is a pain and can be handled in a separate PR. Three final requests and then I think we should be good to merge.

**Add a unit test**. This script https://github.com/dwadden/dygiepp/blob/allennlp-v1/dygie/tests/data/document_test.py runs unit tests to confirm that the `Document` class can read in a document, write it to file, and read it back in without changing it. It should be sufficient to 
1. Create a new text fixture in this directory https://github.com/dwadden/dygiepp/tree/allennlp-v1/dygie/tests/fixtures with event clusters included.
2. Add your new test fixture at this line: https://github.com/dwadden/dygiepp/blob/allennlp-v1/dygie/tests/data/document_test.py#L55.

**Add this field to the documentation**. In particular, add it to the section on `Optional Annotation Fields` here: https://github.com/dwadden/dygiepp/blob/allennlp-v1/doc/data.md#data-format.

**Throw an error if the user attempts to split a document with event clusters**: Just throw an error like what happens here: https://github.com/dwadden/dygiepp/blob/allennlp-v1/dygie/data/dataset_readers/document.py#L191.

Thanks again!

**Comment by khuangaf** [comment]
Hey @dwadden, I just completed the three tasks! The unit test on the new event coreference fixture has been run and passed. Let me know if you have any questions!

**Comment by dwadden** [comment]
Shoot, I deleted the branch that this PR was intended for. Can you just re-submit it to the new `master` branch and I'll OK it?

**Pull request closed without merging**
