### PR TITLE
Adds unit test and span based entities to spacy interface

### PR DESCRIPTION
**Pull request by e3oroush**
Hi  
I just added the unit test and span based entities for the spaCy interface, discussed  [#81](https://github.com/dwadden/dygiepp/pull/81)

### CODE REVIEW

**Comment by dwadden** [comment]
Thanks for the test! A couple minor things before merging:

- Run a code formatter over the submitted files. I unfortunately never set a consistent convention for this. [Black](https://black.readthedocs.io/en/stable/) is one good option, but any formatter is fine.
- In the Jupyter notebook demo, the fourth detected entity is a single newline. Can you confirm that this is the result of a bad DyGIE prediction, not a mistake in piping the DyGIE output into Spacy?
- Also in the notebook, can you convert the line `text = ""Title: VocGan...` into multiple lines for readability? 

After that, I think we're good to merge.

**Comment by e3oroush** [comment]
Those were new line characters. I simply preprocessed the text to get rid of them.   
I think I did all the items you asked in this PR. :smiling_face_with_tear:

**Comment by dwadden** [comment]
Works for me. Merging. Thanks again for adding this!

**Comment by e3oroush** [comment]
No problem at all. Glad to it's useful.

**Pull request merged**
